set SEVENZIP_HOME="C:\Program Files\7-Zip"
set PYINSTALLER_HOME="C:\pyinstaller-2.0"
set JAP_WS_LOCAL_PYTHON_VERSION=2.0.0-SNAPSHOT
set JAP_WS_LOCAL_PYTHON_WINDOWS_VERSION=2.0.0-SNAPSHOT
if exist MAKE rmdir MAKE /s /q
mkdir MAKE
cd MAKE
rem JAP_WS_LOCAL_PYTHON
mkdir JAP_WS_LOCAL_PYTHON-%JAP_WS_LOCAL_PYTHON_VERSION%
cd JAP_WS_LOCAL_PYTHON-%JAP_WS_LOCAL_PYTHON_VERSION%
copy ..\..\JAP_WS_LOCAL.bat JAP_WS_LOCAL.bat
copy ..\..\JAP_WS_LOCAL.json JAP_WS_LOCAL.json
copy ..\..\JAP_WS_LOCAL.py JAP_WS_LOCAL.py
copy ..\..\CA.pem CA.pem
copy ..\..\README.txt README.txt
mkdir JAP
cd JAP
copy ..\..\..\JAP\__init__.py __init__.py
copy ..\..\..\JAP\JAP_LOCAL.py JAP_LOCAL.py
copy ..\..\..\JAP\TUNNEL.py TUNNEL.py
copy ..\..\..\JAP\JAP_WS_LOCAL.py JAP_WS_LOCAL.py
cd ..
cd ..
%SEVENZIP_HOME%\7z.exe a -tzip JAP_WS_LOCAL_PYTHON-%JAP_WS_LOCAL_PYTHON_VERSION%.zip JAP_WS_LOCAL_PYTHON-%JAP_WS_LOCAL_PYTHON_VERSION%
rem JAP_WS_LOCAL_PYTHON_WINDOWS
mkdir PYINSTALLER
cd PYINSTALLER
python %PYINSTALLER_HOME%\pyinstaller.py -c -F ..\..\JAP_WS_LOCAL.py
cd ..
mkdir JAP_WS_LOCAL_PYTHON_WINDOWS-%JAP_WS_LOCAL_PYTHON_WINDOWS_VERSION%
cd JAP_WS_LOCAL_PYTHON_WINDOWS-%JAP_WS_LOCAL_PYTHON_WINDOWS_VERSION%
copy ..\PYINSTALLER\dist\JAP_WS_LOCAL.exe JAP_WS_LOCAL.exe
copy ..\..\JAP_WS_LOCAL_PYTHON_WINDOWS\JAP_WS_LOCAL.bat JAP_WS_LOCAL.bat
copy ..\..\JAP_WS_LOCAL_PYTHON_WINDOWS\README.txt README.txt
copy ..\..\JAP_WS_LOCAL.json JAP_WS_LOCAL.json
copy ..\..\CA.pem CA.pem
cd ..
%SEVENZIP_HOME%\7z.exe a -tzip JAP_WS_LOCAL_PYTHON_WINDOWS-%JAP_WS_LOCAL_PYTHON_WINDOWS_VERSION%.zip JAP_WS_LOCAL_PYTHON_WINDOWS-%JAP_WS_LOCAL_PYTHON_WINDOWS_VERSION%
cd ..