#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cd ${OPENSHIFT_REPO_DIR}
${OPENSHIFT_DATA_DIR}/bin/npm --cache=${OPENSHIFT_DATA_DIR}/.npm --tmp=${OPENSHIFT_TMP_DIR} install