#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT

cd ${OPENSHIFT_REPO_DIR}
nohup ${OPENSHIFT_DATA_DIR}/bin/node server.js >> ${OPENSHIFT_DIY_LOG_DIR}/server.log 2>&1&