#!/bin/bash
# The logic to stop your application should be put in this script.

source ${OPENSHIFT_DATA_DIR}/virtualenv/bin/activate
if [ -f ${OPENSHIFT_TMP_DIR}/twistd.pid ]; then
    kill `cat ${OPENSHIFT_TMP_DIR}/twistd.pid`
fi
exit 0